Valor = (input("Digite algo :"))
print(f" o tipo primitivo deste valor é: {type(Valor)}")
print(f"só tem espaços? {Valor.isspace()}")
print(f"é um número? {Valor.isnumeric()}")
print(f"é alfabético? {Valor.isalpha()}")
print(f"é alfanumérico? {Valor.isalnum()}")
print(f"Está em maiúsculas? {Valor.isupper()}")
print(f"Está em minúsculas? {Valor.islower()}")
print(f"Está capitalizada? {Valor.istitle()}")