Valor = (input("Digite algo :"))
Valor_sem_espaco = Valor.strip()
print(f" o tipo primitivo deste valor é: {type(Valor_sem_espaco)}")
print(f"só tem espaços? {Valor.isspace()}")
print(f"é um número? {Valor_sem_espaco.isnumeric()}")
print(f"é alfabético? {Valor_sem_espaco.isalpha()}")
print(f"é alfanumérico? {Valor_sem_espaco.isalnum()}")
print(f"Está em maiúsculas? {Valor_sem_espaco.isupper()}")
print(f"Está em minúsculas? {Valor_sem_espaco.islower()}")
print(f"Está capitalizada? {Valor_sem_espaco.istitle()}")